<?php

namespace App\Http\Requests\Settings;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

/**
 * Validates the confirmation step when enabling TOTP-based Two-Factor Authentication.
 *
 * Expects a 6-digit numeric code generated by the authenticator app. The user
 * must have begun TOTP setup already; this request only validates the input.
 */
class ConfirmTotpRequest extends FormRequest
{
    /**
     * Authorize the request.
     *
     * This endpoint is available to authenticated users managing their own security settings.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules for confirming TOTP.
     *
     * @return array<string, ValidationRule|array<mixed>|string> Fields:
     *                                                           - code: required 6-character string (TOTP code).
     */
    public function rules(): array
    {
        return [
            'code' => ['required', 'string', 'min:6', 'max:6'],
        ];
    }
}
