<?php

namespace App\Services\TwoFactor\Strategies;

use App\Models\User;
use App\Services\TwoFactor\Contracts\TwoFactorStrategy;
use App\Services\TwoFactor\TotpService;
use Illuminate\Contracts\Session\Session as SessionContract;

/**
 * Implementation of two-factor authentication using Time-based One-Time Password (TOTP).
 *
 * This strategy uses TOTP authentication, where the user must provide a time-based
 * code generated by an authenticator app to verify their identity.
 */
class TotpTwoFactorStrategy implements TwoFactorStrategy
{
    public function __construct(public TotpService $totp) {}

    /**
     * Begin the TOTP challenge for the user.
     *
     * For TOTP authentication, no initial challenge needs to be sent as the code
     * is generated by the user's authenticator app.
     */
    public function beginChallenge(User $user, SessionContract $session): void
    {
        // For TOTP, there is nothing to send. Keep as no-op.
    }

    /**
     * Verify the provided TOTP code against the user's secret.
     *
     * @param  User  $user  The user attempting verification
     * @param  string  $code  The TOTP code provided by the user
     * @param  SessionContract  $session  The current session
     * @return bool True if the code is valid, false otherwise
     */
    public function verify(User $user, string $code, SessionContract $session): bool
    {
        return $this->totp->verify($user->two_factor_secret, $code);
    }
}
