<?php

namespace App\Services\TwoFactor\Strategies;

use App\Enums\TwoFactorType;
use App\Models\User;
use App\Services\TwoFactor\Contracts\TwoFactorStrategy;
use App\Services\TwoFactor\TotpService;
use App\Services\TwoFactor\TwoFactorSessionService;
use Illuminate\Contracts\Session\Session as SessionContract;

/**
 * Implementation of two-factor authentication using Time-based One-Time Password (TOTP).
 *
 * This strategy uses TOTP authentication, where the user must provide a time-based
 * code generated by an authenticator app to verify their identity.
 */
class TotpTwoFactorStrategy implements TwoFactorStrategy
{
    /**
     * Create a new TotpTwoFactorStrategy instance.
     *
     * @param  TotpService  $totp  TOTP generator/verifier
     * @param  TwoFactorSessionService  $sessionService  Central 2FA session helper
     */
    public function __construct(protected TotpService $totp, protected TwoFactorSessionService $sessionService) {}

    /**
     * Begin the TOTP challenge for the user.
     *
     * For TOTP authentication, no initial challenge needs to be sent as the code
     * is generated by the user's authenticator app.
     */
    public function beginChallenge(User $user, SessionContract $session): void
    {
        // For TOTP, there is nothing to send. Keep as no-op.
    }

    /**
     * Verify the provided TOTP code against the user's secret.
     */
    public function verify(User $user, string $code, SessionContract $session): bool
    {
        return $this->totp->verify($user->two_factor_secret, $code);
    }

    /**
     * Check if TOTP setup is in progress for the user.
     *
     * Setup is considered in progress if:
     * - User has selected TOTP as their 2FA type
     * - 2FA is not yet enabled
     * - Either setup was initiated in the current session, OR a secret exists
     */
    public function isSetupInProgress(User $user, SessionContract $session): bool
    {
        if (! $user->isTwoFactorTypeOf(TwoFactorType::Totp) || $user->two_factor_enabled) {
            return false;
        }

        return $this->sessionService->isTotpSetupBegan($session) || ! empty($user->two_factor_secret);
    }

    /**
     * Check if the TOTP setup modal should be automatically displayed.
     *
     * The modal is considered pending if:
     * - User has selected TOTP as their 2FA type
     * - 2FA is not yet enabled
     * - Setup was initiated in the current session
     */
    public function isModalPending(User $user, SessionContract $session): bool
    {
        // For TOTP, modal shows automatically when setup has just begun in this session
        return $user->isTwoFactorTypeOf(TwoFactorType::Totp)
            && ! $user->two_factor_enabled
            && $this->sessionService->isTotpSetupBegan($session);
    }
}
